// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package productModule

import (
	"github.com/google/wire"
	"productConsumer/pkg/helpers"
	"productConsumer/pkg/repos/implement"
	"productConsumer/pkg/repos/interfaces"
)

// Injectors from wire.go:

func InitialProductController() *ProductController {
	db := helpers.NewSqlSession()
	productRepo := implement.NewProductRepo(db)
	productService := NewProductService(productRepo)
	productController := NewProductController(productService)
	return productController
}

// wire.go:

var ProductRepo = wire.NewSet(implement.NewProductRepo, wire.Bind(new(interfaces.IproductRepo), new(*implement.ProductRepo)))
