// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mailModule

import (
	"mailConsumer/pkg/repos/implement"
)

// Injectors from wire.go:

func InitialMailController() *MailController {
	mailRepo := implement.NewMailRepo()
	mailService := NewMailService(mailRepo)
	mailController := NewMailController(mailService)
	return mailController
}
